#!/bin/bash

#/usr/sbin/oo-accept-node > /dev/null
PASS=$(/usr/sbin/oo-accept-broker 2>&1 | grep "PASS")

if [ "$PASS" == "PASS" ]; then
  echo "NODE OK"
  /usr/sbin/oo-accept-broker -v
  exit 0
else
  echo "Node no longer accepted, please verify"
  /usr/sbin/oo-accept-broker -v
  echo "After call"
  exit 2
fi
